# Generated by Django 4.2.7 on 2023-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbnb',
            old_name='locaion',
            new_name='location',
        ),
        migrations.AddField(
            model_name='airbnb',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
