# Generated by Django 4.2.7 on 2023-11-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_rename_locaion_airbnb_location_airbnb_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airbnb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airbnb.airbnb'),
        ),
    ]
