# Generated by Django 4.2.7 on 2023-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_booking_airbnb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
