# Generated by Django 4.2.7 on 2023-11-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0008_airbnb_image_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnb',
            name='image',
        ),
        migrations.CreateModel(
            name='Airbnbimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('airbnb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airbnb.airbnb')),
            ],
        ),
    ]
