# Generated by Django 4.2.7 on 2023-11-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0010_remove_customer_id_customer_airbnb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='airbnb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.airbnb'),
        ),
    ]
