# Generated by Django 4.2.7 on 2023-11-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movers.service'),
        ),
    ]
