# Generated by Django 4.2.7 on 2023-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0004_remove_customer_id_customer_booking_id_customer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_areas',
            field=models.TextField(default='kisumu'),
        ),
    ]
